FROM nginx:1.19.3
COPY redoc.html /usr/share/nginx/html/api/docs/redoc.html
COPY openapi-schema.yml /usr/share/nginx/html/api/docs/openapi-schema.yml
COPY nginx.conf /etc/nginx/templates/default.conf.template