version: '2.25.0'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    env_file: .env

    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alexeyageev/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/recipes/images/
    depends_on:
      - db

  frontend:
    image: alexeyageev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  nginx:
    image: alexeyageev/foodgram_gateway
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
  